__all__ = ['SEQUENCE_COLLECTION_OPERATION', 'MQTT_HOST', 'MQTT_PORT', 'MQTT_TOPIC_COMMAND', 'MQTT_TOPIC_RESULT',
           'MQTT_QOS']

SEQUENCE_COLLECTION_OPERATION = 'operation'
MQTT_HOST = '192.168.1.222'
MQTT_PORT = 1883
MQTT_TOPIC_COMMAND = 'command'
MQTT_TOPIC_RESULT = 'result'
MQTT_QOS = 1

