__all__ = ['DATABASE', 'COLLECTION_OPERATION', 'COLLECTION_SEQUENCE', 'COLLECTION_USER']

DATABASE = 'lemur'
COLLECTION_OPERATION = 'operation'
COLLECTION_SEQUENCE = 'sequence'
COLLECTION_USER = 'user'
