__all__ = ['DATABASE_HOST', 'DATABASE_PORT', 'DATABASE', 'COLLECTION_OPERATION', 'COLLECTION_USER',
           'COLLECTION_SEQUENCE']

DATABASE_HOST = 'localhost'
DATABASE_PORT = 27017
DATABASE = 'lemur'
COLLECTION_OPERATION = 'operation'
COLLECTION_USER = 'user'
COLLECTION_SEQUENCE = 'sequence'
